= Welcome To The Full-Stack Starter Project

This project will assist you in building the critical skills necessary to complete tasks concerning both the Front-End (React) and Back-End (Java) of a web application.

. Fork this repository. In the top right of this page you'll see a fork option. Click that and accept all the default options.
. Now you should be in your users forked repo. To verify this you should see `your.username/fullstack-starter` in the top left/url.
. Clone your forked repository to your environment via git+ssh:

    git clone git@github.com:petersm8/fullstack-starter.git

== Setup

Install java 11

Install gradle https://gradle.org/releases/ (8.6)

Insstall nodejs https://nodejs.org/en/download 

add to env variables path

Install Mongodb https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-windows/ (Also install compass for the GUI)

remove BROWSER = NONE from ui/package.json

import in mongodb compass database start and 2 collection inventory and product (import from sample_data)


== Back-End
The backend java code can be found in the `starter` folder.

. In order to run the web application, we need to compile, or "build", the data objects and classes from the back-end. Enter the following command:

    gradlew build

. Next, we are ready to run the back-end of the application. Enter the following command:

    gradlew bootRun

== Front-End
The front end part of the project can be found in the `ui` folder.

. In order to run the front-end, we must first resolve any dependencies that the project relies on. Enter the following command:

    npm install

. After the dependencies have been resolved, we are ready to run the front-end of the application. In the same directory, enter the following command:

    npm start

. Lastly, to view the operating front-end, navigate to https://localhost:3000[localhost:3000] in your preferred browser.


EVERYTIME
start mongo
boot gradle
boot npm


